adding github actions pipelines
stakater-docker/nexus3 pull request #4
Opened 2022-03-09 06:55 UTC by TehreemNisa

2022-03-09 11:23 UTC, usamaahmadkhan requested changes

2022-03-09 11:23 UTC, usamaahmadkhan commented on .github/workflows/pull_request.yml
> +        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
GITHUB_TOKEN: ${{ secrets.STAKATER_GITHUB_TOKEN }}

2022-03-09 11:23 UTC, usamaahmadkhan commented on .github/workflows/push.yml
> +        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
GITHUB_TOKEN: ${{ secrets.STAKATER_GITHUB_TOKEN }}

2022-03-09 11:23 UTC, usamaahmadkhan commented on .github/workflows/release.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
GITHUB_TOKEN: ${{ secrets.STAKATER_GITHUB_TOKEN }}

2022-03-09 12:05 UTC, TehreemNisa commented on .github/workflows/pull_request.yml
> +        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
updated

2022-03-09 12:05 UTC, TehreemNisa commented on .github/workflows/release.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
updated

2022-03-09 12:05 UTC, TehreemNisa commented on .github/workflows/push.yml
> +        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
updated

2022-03-10 08:38 UTC, usamaahmadkhan approved these changes

2022-03-10 08:40 UTC, stakater-user approved these changes

2022-03-10 08:40 UTC, closed without merging